load File.expand_path("../tasks/framework.rake", __FILE__)
load File.expand_path("../tasks/authorize.rake", __FILE__)
load File.expand_path("../tasks/bootstrap.rake", __FILE__)
load File.expand_path("../tasks/preflight.rake", __FILE__)
load File.expand_path("../tasks/deploy.rake", __FILE__)